/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author Álvaro
 */
public class LateralFrame extends javax.swing.JFrame implements MouseListener{
    
    private final Border bordeNormal = null;
    private final Border bordeEnemigo = BorderFactory.createLineBorder(Color.RED);
    private final Border bordeSelec = BorderFactory.createLineBorder(Color.BLUE);
    private final Border bordeMovimiento = BorderFactory.createLineBorder(Color.BLACK);
    private final Border bordeRaton = BorderFactory.createLineBorder(Color.CYAN);
    
    // QUITAR DESPUES
    int contador;
    private Unidad unidadTemp;
    // QUITAR DESPUES
    
    private TableroFrame tablero;
    private Celda[][] celdas;
    
    /**
     * Creates new form LateralFrame
     */
    public LateralFrame() {
        initComponents();
        tablero = Juego.tableroF;
        this.setLocation(5, 5);
    }
    
    public void tableroCerrando(){
        this.btnTablero.setSelected(false);
    }
    
    public void buscaMovimientos(int desplazamiento, Celda celda){
        contador = 0;
        buscador(desplazamiento, celda, null);
        //buscador(desplazamiento, celda, false);
        System.out.println(contador);
        //celdaComprobada = null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTablero = new javax.swing.JToggleButton();
        cBoxSize = new javax.swing.JComboBox<>();
        btnFigura = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponme un nombre");

        btnTablero.setText("Tablero");
        btnTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroActionPerformed(evt);
            }
        });

        cBoxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediano", "Pequeño" }));
        cBoxSize.setSelectedIndex(1);
        cBoxSize.setToolTipText("");
        cBoxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxSizeActionPerformed(evt);
            }
        });

        btnFigura.setText("Test FIGURA");
        btnFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiguraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnFigura)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(btnFigura)
                .addGap(47, 47, 47)
                .addComponent(cBoxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTablero)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroActionPerformed
        // TODO add your handling code here:
        if(btnTablero.isSelected()){
            if(celdas == null)
                celdas = tablero.getCeldas();
            tablero.setVisible(true);
        } else{
            tablero.setVisible(false);
        }
    }//GEN-LAST:event_btnTableroActionPerformed

    private void cBoxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxSizeActionPerformed
        // TODO add your handling code here:
        switch(this.cBoxSize.getSelectedIndex()){
            case 0:
                tablero.redimensionar('G');
                break;
            case 1:
                tablero.redimensionar('M');
                break;
            case 2:
                tablero.redimensionar('P');
                break;
        }
    }//GEN-LAST:event_cBoxSizeActionPerformed

    private void btnFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiguraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFigura;
    private javax.swing.JToggleButton btnTablero;
    private javax.swing.JComboBox<String> cBoxSize;
    // End of variables declaration//GEN-END:variables

    
    private void buscador(int desplazamiento, Celda celdaInicial, Celda celdaAnterior){
        contador++;
        int indiceY = celdaInicial.getIndiceY();
        int indiceX = celdaInicial.getIndiceX();
        if((celdaInicial.isEmpty()) || celdaAnterior == null){
            celdaInicial.setBorder(bordeMovimiento);
            celdaInicial.setMarcada(true);
            if(desplazamiento!= 0){
                for(int i = indiceY - 1; i <= indiceY + 1; i++){
                    for(int j = indiceX - 1; j <= indiceX + 1; j++){
                        try{
                            if((celdaAnterior == null || !celdaAnterior.equals(celdas[i][j])) &&
                            (celdas[i][j].getIndiceY() == celdaInicial.getIndiceY() || celdas[i][j].getIndiceX() == celdaInicial.getIndiceX())){
                                
                                buscador(desplazamiento-1,celdas[i][j],celdaInicial);
                            }
                         }catch(ArrayIndexOutOfBoundsException aioobe){}
                    }
                }
            }
        } else if(!celdaInicial.isEmpty()){
            celdaInicial.setBorder(bordeEnemigo);
            celdaInicial.setMarcada(true);
        }
    }
    
    private void liberaEstadoCeldas() {
        for(Celda[] celdasArr : celdas){
            for(Celda celda : celdasArr){
                celda.setSelected(false);
                celda.setMarcada(false);
                celda.setBorder(bordeNormal);
            }
        }
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        Celda celda = (Celda) e.getSource();
        System.out.println(
                "¡Clic en celda: ["+celda.getIndiceY()+","+celda.getIndiceX()+"]!"
        );
    }

    @Override
    public void mousePressed(MouseEvent e) {
        Celda celda = (Celda) e.getSource();
        System.out.println(
                "¡PULSADO: ["+celda.getIndiceY()+","+celda.getIndiceX()+"]!"
        );
        
        if(SwingUtilities.isLeftMouseButton(e)){
            if(this.btnFigura.isSelected()){
                unidadTemp = new Unidad();
                unidadTemp.setMovimientos(3);
                unidadTemp.setImg("./imagenes/mal/gorbag.jpg");
                celda.setUnidad(unidadTemp);
            }
            else if(!celda.isEmpty()){
               liberaEstadoCeldas();
               celda.setSelected(true);
               buscaMovimientos(celda.getUnidad().getMovimientos(),celda);
               celda.setBorder(bordeSelec);
            }
            celda.repaint();
        }
        else if(SwingUtilities.isRightMouseButton(e)){
            if(!celda.isEmpty()){
                liberaEstadoCeldas();
                celda.quitaUnidad();
                celda.repaint();
            }
        }
        else if(SwingUtilities.isMiddleMouseButton(e)){
            System.out.println(celda.isEmpty() ? "Esta vacia" : "Tiene figura");
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Celda celda = (Celda) e.getSource();
        System.out.println(
                "¡SOLTADO: ["+celda.getIndiceY()+","+celda.getIndiceX()+"]!"
        );
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        Celda celda = (Celda) e.getSource();
        if(!celda.isSelected() && !celda.isMarcada()){
            celda.setBorder(bordeRaton);
            
        }
        // BLOQUE DE PRUEBA DE RENDIMIENTO DEL METODO DE BUSQUEDA
        /*
        liberaEstadoCeldas();
        celda.setSelected(true);
        buscaMovimientos(1,celda);
        celda.setBorder(BorderFactory.createLineBorder(Color.BLUE,3));
        */
        celda.oscurece();
        System.out.println(
                "¡El puntero entra en la celda: ["+celda.getIndiceY()+","+celda.getIndiceX()+"]!"
        );
    }

    @Override
    public void mouseExited(MouseEvent e) {
        Celda celda = (Celda) e.getSource(); 
        if(!celda.isSelected() && !celda.isMarcada()){
            celda.setBorder(bordeNormal);
        }
        celda.aclara();
    }
}
