/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.vista;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import juego.controlador.BD;
import juego.controlador.ControladorPartida;
import juego.controlador.Sonidos;
import juego.modelo.Unidad;

/**
 *
 * @author Adrian
 */
public class DespliegueFrame extends javax.swing.JFrame {

    private final ControladorPartida controladorPartida;
    private String faccion;
    private Unidad unidadSelec;
    

    /**
     * Creates new form DespliegueFrame
     */
    public DespliegueFrame(ControladorPartida controladorPartida) {
        initComponents();
        this.setLocation(5, 5); 
        this.controladorPartida = controladorPartida;
        this.controladorPartida.setDespliegueFrame(this);
        cargaUnidades();
    }

    private void cargaUnidades() {
        cBoxUnidades.removeAllItems();
        faccion = controladorPartida.getPartida().getJugadorActual().getFaccion();
        for(Unidad unidad : BD.getUnidades(faccion)){
            cBoxUnidades.addItem(unidad);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        txtJuActual = new javax.swing.JLabel();
        cBoxUnidades = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHeridas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFuerza = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDefensa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCombate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMovimientos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCoste = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JTextField();
        btnFin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPuntosDespues = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelImagen.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        txtJuActual.setFont(new java.awt.Font("Ringbearer", 1, 36)); // NOI18N
        txtJuActual.setForeground(new java.awt.Color(255, 255, 255));
        txtJuActual.setText("JUGADOR 1");
        txtJuActual.setToolTipText("");

        cBoxUnidades.setBackground(new java.awt.Color(204, 255, 255));
        cBoxUnidades.setFont(new java.awt.Font("Ringbearer", 0, 11)); // NOI18N
        cBoxUnidades.setForeground(new java.awt.Color(255, 255, 255));
        cBoxUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxUnidadesActionPerformed(evt);
            }
        });
        cBoxUnidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cBoxUnidadesKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Heridas");

        txtHeridas.setEditable(false);
        txtHeridas.setBackground(new java.awt.Color(0, 0, 0));
        txtHeridas.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtHeridas.setForeground(new java.awt.Color(255, 255, 255));
        txtHeridas.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fuerza");

        txtFuerza.setEditable(false);
        txtFuerza.setBackground(new java.awt.Color(0, 0, 0));
        txtFuerza.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtFuerza.setForeground(new java.awt.Color(255, 255, 255));
        txtFuerza.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Defensa");
        jLabel4.setToolTipText("");

        txtDefensa.setEditable(false);
        txtDefensa.setBackground(new java.awt.Color(0, 0, 0));
        txtDefensa.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtDefensa.setForeground(new java.awt.Color(255, 255, 255));
        txtDefensa.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Combate");

        txtCombate.setEditable(false);
        txtCombate.setBackground(new java.awt.Color(0, 0, 0));
        txtCombate.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtCombate.setForeground(new java.awt.Color(255, 255, 255));
        txtCombate.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Movimientos");

        txtMovimientos.setEditable(false);
        txtMovimientos.setBackground(new java.awt.Color(0, 0, 0));
        txtMovimientos.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        txtMovimientos.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coste");
        jLabel7.setToolTipText("");

        txtCoste.setEditable(false);
        txtCoste.setBackground(new java.awt.Color(0, 0, 0));
        txtCoste.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtCoste.setForeground(new java.awt.Color(255, 255, 255));
        txtCoste.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Puntos");
        jLabel8.setToolTipText("");

        txtPuntos.setEditable(false);
        txtPuntos.setBackground(new java.awt.Color(0, 0, 0));
        txtPuntos.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtPuntos.setForeground(new java.awt.Color(255, 255, 255));
        txtPuntos.setFocusable(false);

        btnFin.setBackground(new java.awt.Color(0, 0, 0));
        btnFin.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        btnFin.setForeground(new java.awt.Color(255, 255, 255));
        btnFin.setText("Terminar desplegado");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Despliega tus unidades");

        jLabel10.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puntos - Coste");

        txtPuntosDespues.setEditable(false);
        txtPuntosDespues.setBackground(new java.awt.Color(0, 0, 0));
        txtPuntosDespues.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtPuntosDespues.setForeground(new java.awt.Color(255, 255, 255));
        txtPuntosDespues.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnFin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)))
                        .addGap(36, 36, 36)
                        .addComponent(cBoxUnidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJuActual)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeridas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPuntosDespues, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(62, 62, 62)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtJuActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cBoxUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHeridas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCombate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtPuntosDespues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxUnidadesActionPerformed
        actualizaDatos();
    }//GEN-LAST:event_cBoxUnidadesActionPerformed

    public void actualizaDatos() {
        unidadSelec = (Unidad) cBoxUnidades.getSelectedItem();
        if(unidadSelec != null){
            txtHeridas.setText(String.valueOf(unidadSelec.getHeridas()));
            txtFuerza.setText(String.valueOf(unidadSelec.getFuerza()));
            txtCombate.setText(String.valueOf(unidadSelec.getCombate()));
            txtMovimientos.setText(String.valueOf(unidadSelec.getMovimientos()));
            txtCoste.setText(String.valueOf(unidadSelec.getCoste()));
            txtDefensa.setText(String.valueOf(unidadSelec.getDefensa()));
            labelImagen.setIcon(new ImageIcon(unidadSelec.getImagen().getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), Image.SCALE_DEFAULT)));
            
            txtPuntos.setText(String.valueOf(controladorPartida.getPartida().getJugadorActual().getPuntos()));
            txtPuntosDespues.setText(String.valueOf(
                controladorPartida.getPartida().getJugadorActual().getPuntos() - unidadSelec.getCoste())
            );
            if(Integer.parseInt(txtPuntosDespues.getText()) <= 0){
                txtPuntosDespues.setBackground(Color.red);
            } else
                txtPuntosDespues.setBackground(null);
        }
    }
    

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
        Sonidos.chasquido();
        if(controladorPartida.getPartida().getJugadorActual().getNumero() == 1){
            controladorPartida.getPartida().nuevoTurno();
            txtJuActual.setText("JUGADOR 2");
            cargaUnidades();
        }
        else{
            controladorPartida.getPartida().resetTurnos();
            controladorPartida.getControladorJuego().startPartida();
            this.dispose();
        }
        
    }//GEN-LAST:event_btnFinActionPerformed

    private void cBoxUnidadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cBoxUnidadesKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnFin.doClick();
    }//GEN-LAST:event_cBoxUnidadesKeyPressed

    public Unidad getUnidadSelec() {
        return unidadSelec;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    public javax.swing.JComboBox cBoxUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JTextField txtCombate;
    private javax.swing.JTextField txtCoste;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JTextField txtFuerza;
    private javax.swing.JTextField txtHeridas;
    private javax.swing.JLabel txtJuActual;
    private javax.swing.JTextField txtMovimientos;
    private javax.swing.JTextField txtPuntos;
    private javax.swing.JTextField txtPuntosDespues;
    // End of variables declaration//GEN-END:variables
}


