/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.vista;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import juego.controlador.BD;
import juego.controlador.ControladorJuego;
import juego.controlador.Sonidos;

/**
 *
 * @author Adrian
 */
public class InicioFrame extends javax.swing.JFrame {
    private Object btnIngresar;
    private final ControladorJuego controladorJuego;

    /**
     * Creates new form InicioFrame
     */
    public InicioFrame(ControladorJuego controladorJuego) {
        initComponents();
        this.getRootPane().setDefaultButton(btnNuevaPartida);
        this.controladorJuego = controladorJuego;
        int width = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation(width / 2 - this.getWidth() / 2, height / 2 - this.getHeight() /2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblJ1 = new javax.swing.JLabel();
        lblJ2 = new javax.swing.JLabel();
        txtJ1 = new javax.swing.JTextField();
        txtJ2 = new javax.swing.JTextField();
        lblBien = new javax.swing.JLabel();
        lblMal = new javax.swing.JLabel();
        btnNuevaPartida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOTR - TRPG");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(null);

        lblTitulo.setBackground(new Color(0,0,0,150));
        lblTitulo.setFont(new java.awt.Font("Ringbearer", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText(" El señor de los anillos");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(80, 20, 320, 32);

        lblJ1.setBackground(new Color(0,0,0,150));
        lblJ1.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        lblJ1.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1.setText("  Jugador 1");
        lblJ1.setToolTipText("");
        lblJ1.setOpaque(true);
        jPanel1.add(lblJ1);
        lblJ1.setBounds(110, 60, 90, 30);

        lblJ2.setBackground(new Color(0,0,0,150));
        lblJ2.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        lblJ2.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2.setText("  Jugador 2");
        lblJ2.setOpaque(true);
        jPanel1.add(lblJ2);
        lblJ2.setBounds(110, 100, 90, 30);

        txtJ1.setBackground(new java.awt.Color(0, 0, 0));
        txtJ1.setFont(lblJ1.getFont());
        txtJ1.setForeground(new java.awt.Color(255, 255, 255));
        txtJ1.setPreferredSize(new java.awt.Dimension(30, 20));
        txtJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJ1ActionPerformed(evt);
            }
        });
        txtJ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJ1KeyPressed(evt);
            }
        });
        jPanel1.add(txtJ1);
        txtJ1.setBounds(210, 60, 90, 30);

        txtJ2.setBackground(new java.awt.Color(0, 0, 0));
        txtJ2.setFont(lblJ1.getFont());
        txtJ2.setForeground(new java.awt.Color(255, 255, 255));
        txtJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJ2ActionPerformed(evt);
            }
        });
        txtJ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJ2KeyPressed(evt);
            }
        });
        jPanel1.add(txtJ2);
        txtJ2.setBounds(210, 100, 90, 30);

        lblBien.setBackground(new Color(0,0,0,150));
        lblBien.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        lblBien.setForeground(new java.awt.Color(255, 255, 255));
        lblBien.setText(" Bien");
        lblBien.setOpaque(true);
        jPanel1.add(lblBien);
        lblBien.setBounds(310, 60, 60, 30);

        lblMal.setBackground(new Color(0,0,0,150));
        lblMal.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        lblMal.setForeground(new java.awt.Color(255, 255, 255));
        lblMal.setText(" Mal");
        lblMal.setOpaque(true);
        jPanel1.add(lblMal);
        lblMal.setBounds(310, 100, 60, 30);

        btnNuevaPartida.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaPartida.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        btnNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaPartida.setText("Nueva Partida");
        btnNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaPartida);
        btnNuevaPartida.setBounds(180, 210, 140, 40);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 190, 0, 0);

        txtPuntos.setBackground(new java.awt.Color(0, 0, 0));
        txtPuntos.setFont(lblJ1.getFont());
        txtPuntos.setForeground(new java.awt.Color(255, 255, 255));
        txtPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntosActionPerformed(evt);
            }
        });
        txtPuntos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPuntosKeyPressed(evt);
            }
        });
        jPanel1.add(txtPuntos);
        txtPuntos.setBounds(210, 160, 90, 30);

        jLabel7.setBackground(new Color(0,0,0,150));
        jLabel7.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("  Puntos");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 160, 90, 30);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/imagenes/fondo.jpg"))); // NOI18N
        lblImagen.setMinimumSize(new java.awt.Dimension(400, 255));
        lblImagen.setPreferredSize(new java.awt.Dimension(400, 255));
        jPanel1.add(lblImagen);
        lblImagen.setBounds(-10, 0, 510, 300);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPartidaActionPerformed
        Sonidos.chasquido();
        if(!BD.conecta()) {
            int resp = JOptionPane.showConfirmDialog(this, "No se puede conectar a la BD. ¿Quieres intentar generarla?.");
            if(resp == 0){
                JOptionPane.showMessageDialog(this, "Generando... Intente de nuevo.");
                BD.generaBD();
            }
        } else {
            if(txtPuntos.getText().equals("") || txtJ1.getText().equals("") || txtJ2.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Rellene todos los campos, porfavor");
            else{
                controladorJuego.startDespliegue(txtJ1.getText(), txtJ2.getText(),Integer.parseInt(txtPuntos.getText()));
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnNuevaPartidaActionPerformed

    private void txtJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJ2ActionPerformed

    private void txtPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntosActionPerformed

    private void txtJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJ1ActionPerformed

    private void txtPuntosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntosKeyPressed
        compruebaEnter(evt);
    }//GEN-LAST:event_txtPuntosKeyPressed

    private void txtJ2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJ2KeyPressed
        compruebaEnter(evt);
    }//GEN-LAST:event_txtJ2KeyPressed

    private void txtJ1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJ1KeyPressed
        compruebaEnter(evt);
    }//GEN-LAST:event_txtJ1KeyPressed

    private void compruebaEnter(KeyEvent evt) {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnNuevaPartida.doClick();
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBien;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblMal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtJ1;
    private javax.swing.JTextField txtJ2;
    private javax.swing.JTextField txtPuntos;
    // End of variables declaration//GEN-END:variables
}
