/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import juego.controlador.ControladorPartida;
import juego.controlador.Sonidos;

/**
 * JFrame que muestra los datos durante la partida
 * @author Álvaro
 */
public class LateralFrame extends javax.swing.JFrame{
    
    private TableroFrame tablero;
    private ControladorPartida controlador;
    
    /**
     * Constructor
     */
    public LateralFrame(ControladorPartida controlador) {
        this.controlador = controlador;
        initComponents(); // Inicia los componentes del diseñador
        this.getContentPane().setBackground( new Color(0,0,0) );
        tablero = controlador.getControladorJuego().getTableroF();
        this.setLocation(5, 5);
        controlador.setLateralFrame(this);
        btnMusica.doClick();
    }

    public void escribeLinea(String linea){
        txtArea.append(linea);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cBoxSize = new javax.swing.JComboBox<>();
        txtHeridas = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelHeridas = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnTurno = new javax.swing.JButton();
        btnMusica = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtFuerza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDefensa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCombate = new javax.swing.JTextField();
        btnRendirse = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOTR - Lateral");
        setMaximumSize(new java.awt.Dimension(300, 685));
        setMinimumSize(new java.awt.Dimension(300, 685));
        setPreferredSize(new java.awt.Dimension(300, 685));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 685));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 685));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 685));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 685));
        jPanel1.setLayout(null);

        cBoxSize.setBackground(new java.awt.Color(204, 255, 255));
        cBoxSize.setFont(new java.awt.Font("Ringbearer", 1, 10)); // NOI18N
        cBoxSize.setForeground(new java.awt.Color(255, 255, 255));
        cBoxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediano", "Pequeño" }));
        cBoxSize.setSelectedIndex(1);
        cBoxSize.setToolTipText("");
        cBoxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxSizeActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxSize);
        cBoxSize.setBounds(10, 590, 123, 33);

        txtHeridas.setEditable(false);
        txtHeridas.setBackground(new java.awt.Color(0, 0, 0));
        txtHeridas.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtHeridas.setForeground(new java.awt.Color(255, 255, 255));
        txtHeridas.setFocusable(false);
        txtHeridas.setRequestFocusEnabled(false);
        jPanel1.add(txtHeridas);
        txtHeridas.setBounds(90, 250, 45, 25);

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Ringbearer", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setFocusable(false);
        txtNombre.setRequestFocusEnabled(false);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(90, 210, 195, 30);

        labelNombre.setBackground(new Color(0,0,0,150));
        labelNombre.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText(" Nombre");
        labelNombre.setOpaque(true);
        jPanel1.add(labelNombre);
        labelNombre.setBounds(10, 210, 70, 30);

        labelHeridas.setBackground(new Color(0,0,0,150));
        labelHeridas.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        labelHeridas.setForeground(new java.awt.Color(255, 255, 255));
        labelHeridas.setText(" Heridas");
        labelHeridas.setOpaque(true);
        jPanel1.add(labelHeridas);
        labelHeridas.setBounds(10, 250, 70, 25);

        labelImagen.setBackground(new java.awt.Color(0, 0, 0));
        labelImagen.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        labelImagen.setFocusable(false);
        labelImagen.setOpaque(true);
        jPanel1.add(labelImagen);
        labelImagen.setBounds(69, 25, 160, 160);

        txtArea.setBackground(new java.awt.Color(0, 0, 0));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtArea.setForeground(new java.awt.Color(255, 255, 255));
        txtArea.setRows(5);
        txtArea.setFocusable(false);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 326, 276, 172);

        btnTurno.setBackground(new java.awt.Color(0, 0, 0));
        btnTurno.setFont(new java.awt.Font("Ringbearer", 1, 10)); // NOI18N
        btnTurno.setForeground(new java.awt.Color(255, 255, 255));
        btnTurno.setText("Pasar turno");
        btnTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurno);
        btnTurno.setBounds(160, 520, 123, 33);

        btnMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMusica.setFont(new java.awt.Font("Ringbearer", 1, 10)); // NOI18N
        btnMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMusica.setText("Música");
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMusica);
        btnMusica.setBounds(10, 520, 123, 32);

        jLabel1.setBackground(new Color(0,0,0,150));
        jLabel1.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Fuerza");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 250, 70, 25);

        txtFuerza.setEditable(false);
        txtFuerza.setBackground(new java.awt.Color(0, 0, 0));
        txtFuerza.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtFuerza.setForeground(new java.awt.Color(255, 255, 255));
        txtFuerza.setFocusable(false);
        jPanel1.add(txtFuerza);
        txtFuerza.setBounds(240, 250, 45, 25);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(145, 257, 0, 14);

        jLabel3.setBackground(new Color(0,0,0,150));
        jLabel3.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Defensa");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 290, 70, 25);

        txtDefensa.setEditable(false);
        txtDefensa.setBackground(new java.awt.Color(0, 0, 0));
        txtDefensa.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtDefensa.setForeground(new java.awt.Color(255, 255, 255));
        txtDefensa.setFocusable(false);
        jPanel1.add(txtDefensa);
        txtDefensa.setBounds(90, 290, 45, 25);

        jLabel4.setBackground(new Color(0,0,0,150));
        jLabel4.setFont(new java.awt.Font("Ringbearer", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Combate");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 290, 70, 25);

        txtCombate.setEditable(false);
        txtCombate.setBackground(new java.awt.Color(0, 0, 0));
        txtCombate.setFont(new java.awt.Font("Ringbearer", 1, 14)); // NOI18N
        txtCombate.setForeground(new java.awt.Color(255, 255, 255));
        txtCombate.setFocusable(false);
        jPanel1.add(txtCombate);
        txtCombate.setBounds(240, 290, 45, 25);

        btnRendirse.setBackground(new java.awt.Color(0, 0, 0));
        btnRendirse.setFont(new java.awt.Font("Ringbearer", 1, 10)); // NOI18N
        btnRendirse.setForeground(new java.awt.Color(255, 255, 255));
        btnRendirse.setText("Rendirse");
        btnRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRendirse);
        btnRendirse.setBounds(160, 590, 123, 33);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/imagenes/fondos/fondo-bien-lateral.png"))); // NOI18N
        lblFondo.setText("jLabel5");
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 338, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxSizeActionPerformed
        // TODO add your handling code here:
        switch(this.cBoxSize.getSelectedIndex()){
            case 0:
                tablero.redimensionar('G');
                break;
            case 1:
                tablero.redimensionar('M');
                break;
            case 2:
                tablero.redimensionar('P');
                break;
        }
    }//GEN-LAST:event_cBoxSizeActionPerformed

    private void btnTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoActionPerformed
        if(!controlador.isDecidiendoPosicion())
            controlador.nuevoTurno();
        else
            JOptionPane.showMessageDialog(tablero, "Tienes que terminar el movimiento");
    }//GEN-LAST:event_btnTurnoActionPerformed

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        if(btnMusica.isSelected()){
            Sonidos.startHiloMusical();
        } else{
            Sonidos.stopHiloMusical();
        }
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnRendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendirseActionPerformed
        if(JOptionPane.showConfirmDialog(tablero, controlador.getPartida().getJugadorActual().getNombre()+", ¿Quieres rendirte?") == 0)
            controlador.rendirse();
    }//GEN-LAST:event_btnRendirseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMusica;
    private javax.swing.JButton btnRendirse;
    private javax.swing.JButton btnTurno;
    private javax.swing.JComboBox<String> cBoxSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHeridas;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCombate;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JTextField txtFuerza;
    private javax.swing.JTextField txtHeridas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public void actualizaDatosSelec(Celda celda) {
        txtNombre.setText(celda.getUnidad().getNombre());
        txtHeridas.setText(String.valueOf(celda.getUnidad().getHeridas()));
        txtFuerza.setText(String.valueOf(celda.getUnidad().getFuerza()));
        txtDefensa.setText(String.valueOf(celda.getUnidad().getDefensa()));
        txtCombate.setText(String.valueOf(celda.getUnidad().getCombate()));
        labelImagen.setIcon(new ImageIcon(celda.getUnidad().getImagen().getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), Image.SCALE_DEFAULT)));
    }

    public void limpiaDatos() {
        txtNombre.setText("");
        txtHeridas.setText("");
        txtFuerza.setText("");
        txtDefensa.setText("");
        txtCombate.setText("");
        labelImagen.setIcon(new ImageIcon(getClass().getResource("/juego/imagenes/J"+controlador.getPartida().getJugadorActual().getNumero()+".png")));
    }

    public void setFondo(String ruta) {
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));
    }
    
    
}
